### ISSUE TITLE
Undefined array key "timed_out"

### ISSUE THREAD

**Issue by neylsongularte** [biigle/laravel-file-cache#11]
https://github.com/biigle/laravel-file-cache/blob/d2fedde41ce85d309be5456aa28494774400ed90/src/FileCache.php#L544

Value of stream_get_meta_data($source):

^ array:6 [▼
  "wrapper_type" => "PHP"
  "stream_type" => "TEMP"
  "mode" => "w+b"
  "unread_bytes" => 0
  "seekable" => true
  "uri" => "php://temp"
]

**Comment by neylsongularte** [comment]
^ ErrorException {#484 ▼
  #message: "Undefined array key "timed_out""
  #code: 0
  #file: "vendor/biigle/laravel-file-cache/src/FileCache.php"
  #line: 545
  #severity: E_WARNING
  trace: {▶}
}

**Comment by neylsongularte** [comment]
Catched in FileCache  line 390

**Comment by mzur** [comment]
Looks like you are using a `php://temp` resource somehow, correct? Which PHP version do you use? `stream_get_meta_data` sems to behave strangely here, as `timed_out` should always be present according to the [docs](https://www.php.net/manual/en/function.stream-get-meta-data.php). This can be caught by checking array key existence but I'd like to know why and how you are using the `temp` resource here, first (before we fix the symptom instead of the cause).

**Comment by neylsongularte** [comment]
I am using php 8.0.9 on macos

**Comment by neylsongularte** [comment]
The search is realized on minio server s3 compatible

**Comment by mzur** [comment]
I still don't know exactly why this happens and the array key is not present (maybe a bug in PHP?). But I released a new version with a check that should fix this error for you, as the check shouldn't hurt...

**Comment by neylsongularte** [comment]
Thanks
